version: "3.9"
services:
    ipfs:
        container_name: ipfs
        image: ipfs/go-ipfs:latest
        ports:
            - 4001:4001
            - 5001:5001
            - 8080:8080
        volumes:
            - ./.docker/cdata/ipfs:/data/ipfs

    # supabase:
    #     container_name: supabase
    #     image: supabase/postgres
    #     ports:
    #         - "54321:5432"
    #     environment:
    #         POSTGRES_PASSWORD: postgres
    #         PGDATA: /postgresql/data/pgdata
    #     volumes:
    #         - ./.docker/cdata/postgres:/postgresql/data/pgdata

    mongo:
        container_name: mongo
        image: mongo:5.0.6
        # restart: always
        ports:
            - 27017:27017
        environment:
            # MONGO_INITDB_ROOT_USERNAME: elsa
            # MONGO_INITDB_ROOT_PASSWORD: elsa1234
            MONGO_INITDB_DATABASE: ctc-store
        volumes:
            - "./.docker/cdata/mongodb:/data/db"

    # mongo-db:
    #     container_name: MongoDB
    #     build:
    #         context: .
    #         dockerfile: ./.docker/Dockerfile.mongoInit
    #     ports:
    #         - "27017:27017"
    #     volumes:
    #         - "./.docker/volumes/mongodb:/.data/mongodb"
# Include scripts in the Dockerfile to run  after the build:
# it should create the databases needed for hosting the app properly
