FROM mongo:5.0.6

EXPOSE 27017

ENV MONGO_INITDB_ROOT_USERNAME=elsa
ENV MONGO_INITDB_ROOT_PASSWORD=elsa1234
ENV MONGO_INITDB_DATABASE=ctc-store

# Include scripts to create the collections

RUN mkdir -p /.data/mongodb
RUN mongod --bind_ip_all --dbpath /.data/mongodb

# Create the database
