# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build
on:
    push:
        branches: [main, dev]
    pull_request:
        branches: [main, dev]

jobs:
    build:
        name: Build on Node ${{ matrix.node }} and ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                node: ["14.x"]
                os: [ubuntu-latest, windows-latest]

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install deps and build (with cache)
              run: yarn

            - name: Build for ${{ matrix.project }} android app
              run:
                  - cd apps/${{ matrix.project }}/android && ./gradlew assembleRelease
              strategy:
                  matrix:
                      project: ["mobile-ctc", "mobile-addo", "mobile-providers"]
