# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
    push:
        branches: [main, dev]
    pull_request:
        branches: [main, dev]

jobs:
    test:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x, 16.x]
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install deps and build (with cache)
              run: yarn

            - name: Test Coverage for Entire Monolith
              run: yarn coverage:ci && echo "Done!"

            - name: Coverage for UI Components
              uses: coverallsapp/github-action@1.1.3
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  flag-name: elsa-ui-${{ matrix.os }}-${{ matrix.node }}
                  base-path: ./packages/ui-react-native
                  path-to-lcov: ./packages/ui-react-native/coverage/lcov.info

            - name: Coveralls GitHub Action
              uses: coverallsapp/github-action@1.1.3
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  flag-name: provider-${{ matrix.os }}-${{ matrix.node }}
                  base-path: ./apps/mobile-providers/
                  path-to-lcov: ./apps/mobile-providers/coverage/lcov.info

    finish:
        needs: test
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                node: ["12.x", "14.x"]
                os: [ubuntu-latest, windows-latest]

        steps:
            - name: Coveralls Finished
              uses: coverallsapp/github-action@master
              with:
                  github-token: ${{ secrets.github_token }}
                  parallel-finished: true
